### ISSUE TITLE
'opposite to' subClassof 'ipsilateral to'? 

### ISSUE THREAD

**Issue by srobb1** [obophenotype/biological-spatial-ontology#16]
Hello,
We at PLANA noticed some strange inferred relationships (example: 'dorsal region' subclassOf 'ventral region'). We tracked it down to 'opposite to' being a subClassOf 'ipsilateral to'.

'opposite to' BSPO:0000113  should not be a child class of 'ipsilateral to' BSPO:0000105 as it is impossible to be both on opposite sides and same sides of something.  'opposite to' BSPO:0000113 will fit better as sibling class to 'part of' BSPO:0000050  (a child class of owl:topObjectProperty)

What is the protocol to make changes to BSPO? Can I edit the owl and make a pull request?

Thanks,
Sofia

**Comment by balhoff** [comment]
> Can I edit the owl and make a pull request?

Please do! Edit this file:
https://github.com/obophenotype/biological-spatial-ontology/blob/master/src/ontology/bspo-edit.obo

I think there are more problems here. I don't think either of these should be subproperties of 'in lateral side of'. Nor should 'contralateral to'. And I don't know how 'contralateral to' is different from  'opposite to'. And you're right none of these should be subproperties of 'part of' either.

**Comment by srobb1** [comment]
Great. Let me and my PLANA buddy think about these other terms. I will get back to you with a plan, and hopefully I can fix up all of these.

**Comment by srobb1** [comment]
i made a pull request: https://github.com/obophenotype/biological-spatial-ontology/pull/17

you can see it there, but i will list the details of my changes here as well:

opposite_to
deleted
is_a: ipsilateral_to ! ipsilateral_to

ipsilateral_to
deleted
is_a: in_lateral_side_of ! in_lateral_side_of

contralateral_to
deleted
is_a: in_lateral_side_of ! in_lateral_side_of

We are wondering what the difference is between 'contralateral to' and 'opposite to' are these really synonyms? or can one be the child of the other?? Right now they are separate terms.

Sofia

**Comment by wdahdul** [comment]
Yes, I agree with the changes in the pull request. Regarding 'contralateral to' and 'opposite to', I think we can say 'contralateral to' is a subtype of 'opposite to', because 'opposite to' applies to other axes besides the left/right axis.

**Comment by srobb1** [comment]
@wdahdul Thanks for looking this over. I made the change you suggested in my pull request. That makes a lot of sense to me.

**Comment by balhoff** [comment]
Thanks!
