### ISSUE TITLE
'in left side of' and 'in right side of' should not be inverses

### ISSUE THREAD

**Issue by balhoff** [obophenotype/biological-spatial-ontology#19]
Given that Z is an instance of, e.g. 'body', and X and Y are left and right arms:

X 'in left side of' Z
and
Y 'in right side of' Z

Z should not be 'in right side of' X, nor 'in left side of' Y.

**Comment by balhoff** [comment]
I think they should instead be disjoint properties.

**Comment by cmungall** [comment]
oh doh, of course - can you make the PR?

**Comment by balhoff** [comment]
Fixed by #22.
