### ISSUE TITLE
lateral_to

### ISSUE THREAD

**Issue by teleaslamellatus** [obophenotype/biological-spatial-ontology#9]
We often use lateral to in arthropod anatomy descriptions (e.g. third cardiac artery is lateral to posterior aorta--'has part' some ('third cardiac artery system' and (lateral_to some ('posterior aorta')))).

Lateral_to is available as an entity from PATO but it would be great to have an object property available from BSPO similar to ventral_to (http://purl.obolibrary.org/obo/BSPO_0000102).

Something like this perhaps:

"x lateral_to y if x is further along the midsagittal plane than y, towards the lateral side."

midsagittal plane is http://purl.obolibrary.org/obo/BSPO_0000009.

Thanks:

István

**Comment by teleaslamellatus** [comment]
@cmungall 
Hi Chris,

Should we use this GitHub for requests or are there any other platforms for BSPO?

Thanks!

**Comment by matentzn** [comment]
What about http://purl.obolibrary.org/obo/BSPO_0000126

That sounds at least similar!

**Comment by teleaslamellatus** [comment]
Hello All,

I guess we should then just use "in lateral side of". I know you will hate me, but we also would need then "in medial side of" :).

Thanks!

István

**Comment by balhoff** [comment]
I don't think these mean the same thing ('in lateral side of' and 'lateral to').

**Comment by uberon** [comment]
Correct, they are different

**Comment by teleaslamellatus** [comment]
That is OK then would it be possible to add lateral to and medial to BSPO or should I just keep these object properties in HAO or AISM?

**Comment by cmungall** [comment]
Let's add to BSPO - the fast way to do this would be to make a pull request, I am not sure if HAO uses this system and if you are familiar?

**Comment by teleaslamellatus** [comment]
Yes, I will do it tomorrow.
Thanks!
István

**Comment by balhoff** [comment]
Fixed by #27.
